In [1]:
import numpy as np

In [2]:
def givens_param(aji,aii):
    #c'est l'atan2 du vecteur(aii,aji)' ?
    if (aji == 0.):
        return (1.,0.)
    elif (np.abs(aji) > np.abs(aii)):
        c = -aii/(aji*np.sqrt(1+(aii/aji)**2))
        s = 1/np.sqrt(1+(aii/aji)**2)
        return (c,s)
    else :
        c = 1/np.sqrt(1+(aji/aii)**2)
        s = -aji/(aii*np.sqrt(1+(aji/aii)**2))
        return (c,s)

In [47]:
def givens(A,b,c,s,i,j):
    ai = A[i:i+1,:]
    aj = A[j:j+1,:]
    bi = b[i:i+1,:]
    bj = b[j:j+1,:]
    A[i:i+1,:] = c*ai - s*aj
    A[j:j+1,:] = s*ai + c*aj
    b[i:i+1,:] = c*bi - s*bj
    b[j:j+1,:] = s*bi + c*bj
    return (A,b)

In [55]:
def factorization(A,b):
    (m,n) = np.shape(A)
    for i in range(n): 
        for j in range(m-1,i,-1): #range(debut,fin,pas)
            print("i = ",i," j = ",j)
            (c,s) = givens_param(A[j,i],A[i,i])
            #if (c,s) != (1.,0.):
            (A,b) = givens(A,b,c,s,i,j)
            print(A)
    return (A,b)

In [56]:
H = np.array([[0.86,0.08,0.47],[0.90,0.47,0.41],[0.22,0.83,0.50]])
(m,n) = np.shape(H)
y = np.ones((m,1))
print("H = \n",H)
print("y = \n",y)
factorization(H,y)

H = 
 [[0.86 0.08 0.47]
 [0.9  0.47 0.41]
 [0.22 0.83 0.5 ]]
y = 
 [[1.]
 [1.]
 [1.]]
i =  0  j =  2
[[ 0.88769364  0.28320581  0.5792539 ]
 [ 0.9         0.47        0.41      ]
 [-0.00686341  0.73391843  0.34084298]]
i =  0  j =  1
[[-1.26412025 -0.53349355 -0.69866771]
 [-1.53200022 -0.70986934 -0.78533299]
 [-0.00686341  0.73391843  0.34084298]]
i =  1  j =  2
[[-1.26412025 -0.53349355 -0.69866771]
 [-1.06016242 -1.02105374 -0.79098163]
 [-0.76680084 -0.22367477 -0.331581  ]]


(array([[-1.26412025, -0.53349355, -0.69866771],
        [-1.06016242, -1.02105374, -0.79098163],
        [-0.76680084, -0.22367477, -0.331581  ]]),
 array([[-1.56630669],
        [-1.74312243],
        [-0.78901641]]))