In [3]:
import numpy as np

In [4]:
def givens_param(aji,aii):
    #computes cos and sin theta such that Givens product (see givens function) cancels y component (aji)
    if (aji == 0.):
        return (1.,0.)
    elif (np.abs(aji) > np.abs(aii)):
        r = (-aii/aji)
        s = 1/np.sqrt(1+r**2)
        c = r*s
        return (c,s)
    else :
        r = (-aji/aii)
        c = 1/np.sqrt(1+r**2)
        s = r*c
        return (c,s)

In [5]:
def givens(A,b,c,s,i,j):
    #applies a Givens rotation to matrix A and vector b, rows i and j
    #c : cos theta
    #s : sin theta
    #if A of size m*n,
    #1<=i<=n
    #i<j<=m
    
    #in python, A[:,:] returns a reference, so we need to make a copy
    ai = np.copy(A[i:i+1,:])
    aj = np.copy(A[j:j+1,:])
    bi = np.copy(b[i:i+1,:])
    bj = np.copy(b[j:j+1,:])
    A[i:i+1,:] = ai*c - aj*s
    A[j:j+1,:] = ai*s + aj*c
    b[i:i+1,:] = c*bi + s*bj
    b[j:j+1,:] = -s*bi + c*bj
    return (A,b)

In [6]:
def factorization(A,b):
    #factorization of system Ax=b
    #returns ([[R],[0]], Q.T*b), with R upper triangular
    (m,n) = np.shape(A)
    for i in range(n): 
        for j in range(m-1,i,-1): #range(debut,fin,pas)
            (c,s) = givens_param(A[j,i],A[i,i])
            if (c,s) != (1.,0.): #if givens_param returns (1.,0.), there is no modification
                (A,b) = givens(A,b,c,s,i,j)
    return (A,b)

In [7]:
def backsubstitution(A,b):
    #backsubstitution
    #A and b computed by factorization function
    #A : [[R],[0]], with R upper triangular
    #b : Q.T*b
    (m,n) = np.shape(A);
    R = A[:n,:n]
    d = b[:n,:]
    return np.linalg.solve(R,d)  #the backsubstitution is applied here

In [9]:
A = np.array([[0.86,0.08,0.47],[0.90,0.47,0.41],[0.22,0.83,0.50],[2.,3.,4.],[2.,3.,4.],[2.,3.,4.],[2.,3.,4.],[2.,3.,4.],[2.,3.,4.]])
#before doing anything else, we should make sure A has more rows than columns and is full rank
#if this is not the case, the call to backsubstitution will raise an error
(m,n) = np.shape(A)
b = np.ones((m,1))
print("A = \n",A)
print("b = \n",b)
(R,d) = factorization(A,b)
print("R = \n",R)
print("d = \n",d)
x = backsubstitution(R,d)
print("x = \n",x)

A = 
 [[0.86 0.08 0.47]
 [0.9  0.47 0.41]
 [0.22 0.83 0.5 ]
 [2.   3.   4.  ]
 [2.   3.   4.  ]
 [2.   3.   4.  ]
 [2.   3.   4.  ]
 [2.   3.   4.  ]
 [2.   3.   4.  ]]
b = 
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
R = 
 [[-5.05944661e+00 -7.24869790e+00 -9.66176813e+00]
 [ 2.24123283e-17  1.54031776e+00  1.69449562e+00]
 [ 2.31613905e-17 -5.13246102e-17 -6.46468289e-01]
 [ 2.21067245e-16  1.52354107e-17  0.00000000e+00]
 [-5.58315064e-19  1.66600867e-18  0.00000000e+00]
 [-7.18966067e-19  2.14539026e-18 -3.46944695e-18]
 [-1.01199420e-18 -2.47829527e-17  0.00000000e+00]
 [-1.73118464e-18 -5.07811687e-17  0.00000000e+00]
 [-1.26427581e-17  3.25470018e-17  0.00000000e+00]]
d = 
 [[ 2.42318991]
 [-1.69960647]
 [ 0.09009139]
 [ 0.01710283]
 [ 0.02091354]
 [ 0.02693126]
 [ 0.0379076 ]
 [ 0.06484727]
 [ 0.47357648]]
x = 
 [[ 1.14840375]
 [-0.95010441]
 [-0.13935933]]
